#!/bin/bash
# =============================================================
# GeoScore — EC2 Ubuntu 22.04 One-Time Setup Script
# Run as: sudo bash setup.sh
# =============================================================
set -euo pipefail

APP_USER="geoscore"
APP_DIR="/opt/geoscore"
DOMAIN=""   # Set this before running: DOMAIN=geoscore.in sudo bash setup.sh

log() { echo -e "\033[1;32m[SETUP]\033[0m $1"; }
warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }
die() { echo -e "\033[1;31m[ERROR]\033[0m $1"; exit 1; }

[[ $EUID -ne 0 ]] && die "Run as root: sudo bash setup.sh"

# ─── 1. System update ────────────────────────────────────────
log "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl wget gnupg2 ca-certificates lsb-release software-properties-common \
  build-essential git unzip htop ufw

# ─── 2. Node.js 20 LTS ────────────────────────────────────────
log "Installing Node.js 20 LTS..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
node --version && npm --version

# Install PM2 globally
npm install -g pm2
pm2 startup systemd -u "$APP_USER" --hp "/home/$APP_USER" 2>/dev/null || true

# ─── 3. PostgreSQL 15 ─────────────────────────────────────────
log "Installing PostgreSQL 15..."
sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
apt-get update -qq
apt-get install -y postgresql-15 postgresql-client-15

# Start and enable PostgreSQL
systemctl start postgresql
systemctl enable postgresql

# Create database and user
log "Creating PostgreSQL database..."
DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/\n" | cut -c1-32)
sudo -u postgres psql <<EOF
CREATE USER geoscore WITH ENCRYPTED PASSWORD '$DB_PASSWORD';
CREATE DATABASE geoscore OWNER geoscore;
GRANT ALL PRIVILEGES ON DATABASE geoscore TO geoscore;
ALTER USER geoscore CREATEDB;
EOF

DATABASE_URL="postgresql://geoscore:${DB_PASSWORD}@localhost:5432/geoscore"
log "Database created. DATABASE_URL: $DATABASE_URL"

# ─── 4. pgAdmin 4 (Web) ────────────────────────────────────────
log "Installing pgAdmin 4..."
curl -fsSL https://www.pgadmin.org/static/packages_pgadmin_org.pub | gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list'
apt-get update -qq
apt-get install -y pgadmin4-web

# Configure pgAdmin web (runs on port 5050 internally)
PGADMIN_EMAIL="admin@${DOMAIN:-localhost}"
PGADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/\n")
/usr/pgadmin4/bin/setup-web.sh --yes <<< "${PGADMIN_EMAIL}
${PGADMIN_PASSWORD}
${PGADMIN_PASSWORD}"

log "pgAdmin installed. Email: $PGADMIN_EMAIL | Password: $PGADMIN_PASSWORD"

# ─── 5. Nginx ─────────────────────────────────────────────────
log "Installing Nginx..."
apt-get install -y nginx
systemctl start nginx
systemctl enable nginx

# ─── 6. Certbot (Let's Encrypt SSL) ───────────────────────────
log "Installing Certbot..."
apt-get install -y certbot python3-certbot-nginx

# ─── 7. App user + directory ──────────────────────────────────
log "Creating app user and directories..."
id "$APP_USER" &>/dev/null || useradd -m -s /bin/bash "$APP_USER"
mkdir -p "$APP_DIR" "$APP_DIR/logs"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

# ─── 8. Firewall ──────────────────────────────────────────────
log "Configuring UFW firewall..."
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw allow 5050/tcp   # pgAdmin
ufw --force enable

# ─── 9. Write .env template ───────────────────────────────────
SESSION_SECRET=$(openssl rand -base64 48 | tr -d "=+/\n")
cat > "$APP_DIR/.env.template" <<ENVEOF
# Auto-generated by setup.sh on $(date)
# FILL IN missing values before running deploy.sh

DATABASE_URL=${DATABASE_URL}
SESSION_SECRET=${SESSION_SECRET}
NODE_ENV=production
PORT=5000
ALLOWED_ORIGINS=https://${DOMAIN:-geoscore.in}

# LLM Providers — fill in the ones you have
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
PERPLEXITY_API_KEY=
GROK_API_KEY=
DEEPSEEK_API_KEY=
OPENROUTER_API_KEY=

# Razorpay
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

# Integrations
BRAND_DEV_API_KEY=
GOOGLE_KG_API_KEY=
SERPAPI_API_KEY=
DATAFORSEO_KEY=

# OAuth
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=https://${DOMAIN:-geoscore.in}/api/auth/google/callback

# Email
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@${DOMAIN:-geoscore.in}
ENVEOF

chown "$APP_USER:$APP_USER" "$APP_DIR/.env.template"

# ─── 10. Nginx config (HTTP — before SSL) ────────────────────
if [[ -n "$DOMAIN" ]]; then
cat > "/etc/nginx/sites-available/geoscore" <<NGINXEOF
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};

    # App proxy
    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        client_max_body_size 10M;
    }

    # pgAdmin at /pgadmin
    location /pgadmin {
        proxy_pass http://localhost:5050;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_redirect off;
    }
}
NGINXEOF

  ln -sf /etc/nginx/sites-available/geoscore /etc/nginx/sites-enabled/
  rm -f /etc/nginx/sites-enabled/default
  nginx -t && systemctl reload nginx

  # ─── 11. SSL Certificate ────────────────────────────────────
  log "Obtaining SSL certificate for $DOMAIN..."
  certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos \
    --email "admin@${DOMAIN}" --redirect || warn "SSL cert failed — run certbot manually after DNS propagates"

  # Auto-renewal cron
  (crontab -l 2>/dev/null; echo "0 12 * * * /usr/bin/certbot renew --quiet") | crontab -
else
  warn "DOMAIN not set — skipping nginx site config and SSL. Set DOMAIN=geoscore.in and re-run."
fi

# ─── 12. Summary ─────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  SETUP COMPLETE"
echo "============================================================"
echo "  App directory:    $APP_DIR"
echo "  Database URL:     $DATABASE_URL"
echo "  pgAdmin email:    $PGADMIN_EMAIL"
echo "  pgAdmin password: $PGADMIN_PASSWORD"
echo "  Session secret:   $SESSION_SECRET (auto-generated)"
echo ""
echo "  NEXT STEPS:"
echo "  1. Copy your project files to $APP_DIR"
echo "  2. Copy $APP_DIR/.env.template to $APP_DIR/.env"
echo "  3. Fill in missing API keys in $APP_DIR/.env"
echo "  4. Run: sudo bash $APP_DIR/deploy/deploy.sh"
echo "============================================================"
